### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by DragonBe** [speckcommerce/SpeckCatalog#115]
# Composer install fails

After cloning my [forked repository](https://github.com/DragonBe/SpeckCatalog) and [grabbing the composer installer](https://getcomposer.org/download/), the first thing I do is to install all composer libraries. 

    php composer.phar install

Unfortuantely it failed immediately.

    [Composer\Json\JsonValidationException]
      "./composer.json" does not match the expected JSON schema:
      - authors[0].homepage : Invalid URL format

Here's the screenshot:

![screenshot 2015-01-01 14 59 44](https://cloud.githubusercontent.com/assets/282825/5592286/03fee2ea-91c7-11e4-98ab-109830bfe9fa.png)

**Comment by Xerkus** [comment]
fixed by #116
