### ISSUE TITLE
Composer issues with package `evandotpro/edp-sub-layout`

### ISSUE THREAD

**Issue by DragonBe** [speckcommerce/SpeckCatalog#117]
Composer installation has a problem installing `evandotpro/edp-sub-layout`

	php composer.phar install
	Loading composer repositories with package information
	Installing dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - The requested package evandotpro/edp-sub-layout could not be found in any version, there may be a typo in the package name.

	Potential causes:
	 - A typo in the package name
	 - The package is not available in a stable-enough version according to your minimum-stability setting
	   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

	Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

The necessary screenshot
![screenshot 2015-01-01 15 45 35](https://cloud.githubusercontent.com/assets/282825/5592392/44196f0c-91cd-11e4-9e56-0e2fcdcbe2a4.png)

Searching for it on [Packagist](http://packagist.org) showed me the package is not there. Either it's not yet available or it has been removed in the past.

![composer_packages_evandotpro_not_found](https://cloud.githubusercontent.com/assets/282825/5592410/015c5188-91ce-11e4-9d86-6180001d6c6c.png)

**Comment by Xerkus** [comment]
fixed by adding package to packagist
